name: Test

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  vitest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.0
      - uses: actions/setup-node@v3.8.1
        with:
          node-version: 18.x
      - run: npm ci
      - run: npm run test
